version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shared-postgres
    environment:
      POSTGRES_PASSWORD: root_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgre/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.5
    container_name: keycloak-server
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_PROFILE_FEATURES: upload_scripts
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/management-realm.json:/opt/keycloak/data/import/management-realm.json
    ports:
      - "8888:8080"
    networks:
      - microservices-network
    depends_on:
      postgres:
        condition: service_healthy
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservices-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "usertopic:1:1,ordertopic:1:1"
    networks:
      - microservices-network

volumes:
  postgres_data:

networks:
  microservices-network:
    name: microservices-network
    driver: bridge
